CONFIGURE_PATH = "./resources/configure.json"
CACHE_CONFIGURE_PATH = "./interface/setting/switch.json"
OPACITY_PRECISION = 100
TOP_P_PRECISION = 100
TEMPERATURE_PRECISION = 100
SPEED_PRECISION = 100
BATCH_THRESHOLD_PRECISION = 100
